USE [master]
GO

/****** Object:  Database [TicketingSystem]    Script Date: 7/16/25 17:45:01 ******/
CREATE DATABASE [TicketingSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TicketingSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017CPE106\MSSQL\DATA\TicketingSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TicketingSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017CPE106\MSSQL\DATA\TicketingSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TicketingSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TicketingSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TicketingSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TicketingSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TicketingSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TicketingSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [TicketingSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TicketingSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TicketingSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TicketingSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TicketingSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TicketingSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TicketingSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TicketingSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TicketingSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TicketingSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TicketingSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TicketingSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TicketingSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TicketingSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TicketingSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TicketingSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TicketingSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TicketingSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [TicketingSystem] SET  MULTI_USER 
GO

ALTER DATABASE [TicketingSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TicketingSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TicketingSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TicketingSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TicketingSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TicketingSystem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TicketingSystem] SET  READ_WRITE 
GO

